import {
  createIcons,
  Home,
  FileText,
  Upload,
  LayoutDashboard,
  Search,
  MessageSquare,
  Settings,
  ShieldCheck,
  Calendar,
  Layers,
  ChevronDown,
  ChevronRight,
  Menu,
  Moon,
  Sun,
  MoreVertical,
  Download,
  Trash2,
  Copy,
  Plus,
  ArrowRight,
  AlertCircle,
  CheckCircle2,
  Lock,
  User,
  LogOut,
  HelpCircle,
  FileSearch,
  BookOpen,
  PieChart,
  Users,
  Briefcase,
  Globe,
  Bell,
  Mail,
  Zap,
  Filter,
  Eye,
  History,
  Archive,
  Star,
  ExternalLink,
  ChevronLeft,
  ChevronsLeft,
  ClipboardCheck,
  Edit3,
  Book,
  PenTool,
  Maximize,
  X
} from 'lucide';

/**
 * Initializes all Lucide icons on the page.
 * Icons should be defined using <i data-lucide="icon-name"></i>.
 */
export function initIcons() {
  createIcons({
    icons: {
      Home,
      FileText,
      Upload,
      LayoutDashboard,
      Search,
      MessageSquare,
      Settings,
      ShieldCheck,
      Calendar,
      Layers,
      ChevronDown,
      ChevronRight,
      Menu,
      Moon,
      Sun,
      MoreVertical,
      Download,
      Trash2,
      Copy,
      Plus,
      ArrowRight,
      AlertCircle,
      CheckCircle2,
      Lock,
      User,
      LogOut,
      HelpCircle,
      FileSearch,
      BookOpen,
      PieChart,
      Users,
      Briefcase,
      Globe,
      Bell,
      Mail,
      Zap,
      Filter,
      Eye,
      History,
      Archive,
      Star,
      ExternalLink,
      ChevronLeft,
      ChevronsLeft,
      ClipboardCheck,
      Edit3,
      Book,
      PenTool,
      Maximize,
      X,
      // Kebab-case fallback aliases
      'file-text': FileText,
      'layout-dashboard': LayoutDashboard,
      'message-square': MessageSquare,
      'shield-check': ShieldCheck,
      'chevron-down': ChevronDown,
      'chevron-right': ChevronRight,
      'more-vertical': MoreVertical,
      'trash-2': Trash2,
      'arrow-right': ArrowRight,
      'alert-circle': AlertCircle,
      'check-circle-2': CheckCircle2,
      'log-out': LogOut,
      'help-circle': HelpCircle,
      'file-search': FileSearch,
      'book-open': BookOpen,
      'pie-chart': PieChart,
      'external-link': ExternalLink,
      'chevron-left': ChevronLeft,
      'chevrons-left': ChevronsLeft,
      'clipboard-check': ClipboardCheck,
      'edit-3': Edit3,
      'pen-tool': PenTool
    },
    attrs: {
      'stroke-width': 2,
      'size': 18,
      'class': 'lucide-icon'
    }
  });
}
